### ISSUE TITLE
New header added ( Amino 3.5.34803 )

### ISSUE THREAD

**Issue by ghost** [Slimakoi/Signatures#2]
A new header request was added in the new version of Amino on mobile.

Ndc-Message-Signature: MEYCIQD2QUNiNvvIBILhcKRFeWt8A4lyYq7q7RIkP0k1tTHYKAIhAJWp3wPZK88BT/O5+XaKrPs6OxTgthhhDUKu5RQKfAgp

I can't say what kind of signature could be. However without this correct signature based on the data sent, it is not possible to send a message using the API.

New data for send message: {"type":0,"inviteeUids":["3e9dbafa-5c5d-41d1-9e14-2dbb1dd028cd"],"initialMessageContent":"oiii","timestamp":1670471678797,"uid":"13ba9145-b33d-4273-8863-e854902f948f"}

This capture I made using Burp Suite.

**Comment by secp192k1** [comment]
That header has been seen a long time ago and once it comes public ill post it here
